name: Build Artifact for Veracode Code Analysis

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
      event_name:
        required: true
        type: string
    outputs:
      veracode_scan_artifact:
        description: 'The Artifact Name'
        value: ${{ jobs.build.outputs.veracode_scan_artifact }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      veracode_scan_artifact: ${{ steps.identify.outputs.veracode_scan_artifact }}
    steps:
    - name: debug
      run: |
        echo ${{ inputs.event_name }}

    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
      
    - name: Identify the Artifact
      id: identify
      run: |
        jar_files=$(find target -name "*.jar" -type f -maxdepth 1 -exec basename {} \;)
        war_files=$(find target -name "*.war" -type f -maxdepth 1 -exec basename {} \;)
        ear_files=$(find target -name "*.ear" -type f -maxdepth 1 -exec basename {} \;)
        if [ ! -z "$jar_files" ]; then
          artifact_file=$jar_files
        elif [ ! -z "$war_files" ]; then
          artifact_file=$war_files
        elif [ ! -z "$ear_files" ]; then
          artifact_file=$ear_files
        else
          echo "no files found"
        fi
        echo $artifact_file
        echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
        echo "veracode_scan_artifact=$artifact_file" >> $GITHUB_OUTPUT
        
    - uses: actions/upload-artifact@v3
      with:
        name: veracode-artifact
        path: target/${{ env.veracode_artifact }}
