name: Reusable workflow

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Hello World"
