name: Veracode Build Java Maven Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - name: Setup .NET
      run: |
        choco install dotnetcore-sdk -y
        dotnet --version
    - name: Build application
      run: |
        dotnet restore
        dotnet publish -c Debug -o ./output
        
    - name: Setup 7zip
      run: |
        choco install 7zip -y
        
    - name: Create zip archive
      run: 7z a -tzip veracode.zip ./output
        
    - uses: actions/upload-artifact@v3
      with:
        name: veracode-artifact
        path: veracode.zip
