name: Veracode Static Code Analysis

on:
  repository_dispatch:
    types: [veracode-policy-scan]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: vincent-deng/veracode-github-app@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: "Central markdown check"
        enforce: true
        
  build:
    needs: [register]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package

    - uses: actions/upload-artifact@v3
      with:
        name: verademo.war
        path: target/verademo.war
        
  veracode-pipeline-scan:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: verademo.war
          path: /tmp
      - name: pipeline-scan
        run: | 
          java -jar /opt/veracode/pipeline-scan.jar \
            -vid "${{secrets.API_ID}}" \
            -vkey "${{secrets.API_KEY}}" \
            --fail_on_severity="Very High, High" \
            --file /tmp/verademo.war \
            -bf ./results.json \
            -jf results.json \
            -fjf filtered_results.json 
        continue-on-error: true

#   policy-scan:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - uses: actions/checkout@v3
#       - name: get archive
#         uses: actions/download-artifact@v3
#         with:
#           name: verademo.war
#           path: .
#       - name: Veracoe Upload and Scan Action Step
#         uses: veracode/veracode-uploadandscan-action@master
#         id: upload_and_scan
#         with:
#           appname: 'VeraDemo - Web - GitHub'
#           createprofile: true
#           version: '${{ github.run_id }}'
#           filepath: 'verademo.war'
#           vid: '${{ secrets.API_ID }}'
#           vkey: '${{ secrets.API_KEY }}'
#           scantimeout: 15
#         continue-on-error: false
