name: Veracode Build Java Maven Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
  
#     runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - name: Setup .NET Core
      run: |
        apt-get update
        apt-get install -y wget
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        apt-get update
        apt-get install -y dotnet-sdk-3.1
    - name: Build and Test
      run: |
        dotnet restore
        dotnet publish -c Debug -o ./output
    - name: Create zip archive
      run: zip -r veracode.zip ./output

#     - name: Setup .NET
#       run: |
#         choco install dotnetcore-sdk -y
#         dotnet --version
#     - name: Build application
#       run: |
#         dotnet restore
#         dotnet publish -c Debug -o ./output
        
#     - name: Setup 7zip
#       run: |
#         choco install 7zip -y
        
#     - name: Create zip archive
#       run: 7z a -tzip veracode.zip ./output
        
    - uses: actions/upload-artifact@v3
      with:
        name: veracode-artifact
        path: veracode.zip
