name: Veracode Static Pipeline Scanner

on:
  workflow_call:
    inputs:
      veracode_scan_artifact:
        required: true
        type: string
  
jobs:
  pipeline_scan:
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
#           path: veracode/
      
      - name: Display structure of downloaded files
        run: ls -R

      # run the pipeline scan action
      - name: Veracode Pipeline-Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.4
        with:
          vid: ${{ secrets.API_ID }}
          vkey: ${{ secrets.API_KEY }}
#           file: ${{ inputs.veracode_scan_artifact }}
          file: "verademo.war"
          fail_build: true
